name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add WASM target
      run: rustup target add wasm32-wasi
    - name: Install cargo-make
      run: cargo install --debug cargo-make
    - name: Build
      run: cargo make build
    - name: Test
      run: cargo make test

  format:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-make
      run: cargo install --debug cargo-make
    - name: Check Format
      run: cargo make check-format

  clippy:
    name: Check Clippy Lints
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-make
      run: cargo install --debug cargo-make
    - name: Check Lints
      run: cargo make clippy -D clippy::all
